### ISSUE TITLE
Google search youtube video popups won't play

### ISSUE THREAD

**Issue by artifoxel** [ronsen/popup-this-video#2]
If you right click > "Popup This Video" on a youtube video within a Google search page, the video will not redirect properly and will display an error message.

Example: https://www.google.com/search?q=foxy+music

![Capture](https://user-images.githubusercontent.com/45717702/60840212-ffcb6280-a19c-11e9-8eb2-fb562b5414a3.PNG)

Here is the youtube debug info:

```
  "debug_error": {
    "errorCode": "api.invalidparam",
    "errorMessage": "An error occurred. Please try again later.",
    "Mp": "GENERIC_WITHOUT_LINK",
    "Ph": "",
    "Qz": "invalidVideodata.1"
  },
```

Any ideas? Maybe it's possible to parse the video url before opening the popup? Thanks a lot! 🦊

**Comment by ronsen** [comment]
Google search modifies all the result links on its page. You need an add-on to remove this. You can use this: https://addons.mozilla.org/en-US/firefox/addon/google-search-link-fix/

**Comment by artifoxel** [comment]
Hey thanks Rosen, I used a [google userscript](https://greasyfork.org/en/scripts/14150-google-%E7%BB%95%E8%BF%87%E6%90%9C%E7%B4%A2%E7%BB%93%E6%9E%9C%E7%BD%91%E9%A1%B5%E9%93%BE%E6%8E%A5%E9%87%8D%E5%AE%9A%E5%90%91) to get rid of those pesky re-directs. 

Everything works! 🦊
